version: "3"
services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:15.5

  node-app:
    container_name: node-app
    build: ./server
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./server/src:/app/src
    environment:
      - PORT=3000
